### ISSUE TITLE
!stream command no longer working 

### ISSUE THREAD

**Issue by bamtan** [DuckBoss/JJMumbleBot#60] opened 2019-04-16 14:33 UTC
<h2>Please have a look at the <a href="https://github.com/DuckBoss/JJMumbleBot/wiki/F.A.Q.">F.A.Q.</a> for solutions to common problems before posting an issue!</h2>

**Describe the bug**
When runinng the stream command, I get the error ```ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))```

**To Reproduce**
1. run the command !stream <yt_url>
2. error log in console

**Expected behavior**
It should begin streaming the song through VLC.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Debian 8
 - Version  v1.7.1_p1 bbb5bc7 
 - Python Version: 3.6.6

**Additional context**
Here's the log
```
JJMumbleBot is Online

INFO:RuntimeLogging:JJ Mumble Bot has fully initialized and joined the server.
Message Received: [bamtan -> Hyperlink Data]
INFO:RuntimeLogging:Commands Received: [bamtan -> !stream <a href="https://www.youtube.com/watch?v=hLakR2NSfFA!">https://www.youtube.com/watch?v=hLakR2NSfFA!</a>]
DEBUG:RuntimeLogging:Removing cache dir /home/bam/.cache/youtube-dl .
DEBUG:RuntimeLogging:.
WARNING:RuntimeLogging:The url doesn't specify the protocol, trying with http
DEBUG:RuntimeLogging:[generic] watch?v=hLakR2NSfFA!: Requesting header
WARNING:RuntimeLogging:Could not send HEAD request to http://%https://www.youtube.com/watch?v=hLakR2NSfFA!: <urlopen error [Errno -2] Name or service not known>
DEBUG:RuntimeLogging:[generic] watch?v=hLakR2NSfFA!: Downloading webpage
ERROR:RuntimeLogging:ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
```

**Comment by DuckBoss** [comment] 2019-04-16 18:41
Hello! Thanks for submitting a report. It seems that there is a problem with the update I made to the !stream/!link command. Currently the !stream command is just an alias to the !link command, however when testing with !link, everything works properly.
I will look into this issue, but in the mean time I suggest using the !link command instead.

**Comment by DuckBoss** [comment] 2019-04-16 18:48
I've looked into this further and I've noticed there's a problem with the way aliases are being parsed. So aliases like !p, !v are currently not functioning as intended. Please use the full-commands !play, !volume while I find a fix.
Thanks for pointing this out!

**Comment by DuckBoss** [comment] 2019-04-16 19:02
I found the issue! When I was updating strings to the new python 3.6+ format, I missed an extra "%" character that made all aliases that required parameters to parse incorrectly.

Please let me know if you run into anymore issues =)
Issue resolved in Release v1.7.1_p2.

**Closed by DuckBoss** 2019-04-16 19:02 UTC
Labels: Fixing, bug, v1.7

**Comment by DuckBoss** [comment] 2019-04-16 19:07
Fixed in this release: <a href="https://github.com/DuckBoss/JJMumbleBot/releases/tag/v1.7.1_p2">v1.7.1_p2</a>

**Comment by bamtan** [comment] 2019-04-17 09:54
Thank you so much!
